### ISSUE TITLE
Feature Request: able to set optional parameters upon get()

### ISSUE THREAD

**Issue by KiddoKenshin** [panakour/google-analytics#2]
Reference: https://github.com/googleapis/google-api-php-client/issues/1385#issuecomment-367301854

Is it possible to add array argument to ::get() to pass extra param to analytics's batchGet()? (See reference)

Example:
```
// Expectation
Analytics::get([
    'quotaUser' => 'something'
]);

public function get($optionalParams = [])
{
    return $this->analytics->reports->batchGet($this->body, $optionalParams);
}
```

Thank you!

**Comment by panakour** [comment]
@KiddoKenshin Now it's not possible. My available time is not enough but I will try in the next days to update the library so you are able to do this.

**Comment by KiddoKenshin** [comment]
@panakour Thank you for consideration :)

**Comment by panakour** [comment]
it's my pleasure :smiley:

**Comment by panakour** [comment]
@KiddoKenshin With https://github.com/panakour/google-analytics/commit/3fcebbc95eb7de9f40f4ca3b4391a54b2efa9db7 you are able to pass your parameters via  `public function setAnalyticsReporting(array $params);`
