### ISSUE TITLE
Undefined index: credentials_json_file

### ISSUE THREAD

**Issue by j3dyy** [panakour/google-analytics#3]
hello i craeted folder in storage/app/google-analytics/
and put inside .json file named service-account-credentials.json . but laravel return error :
Undefined index: credentials_json_file

**Comment by panakour** [comment]
Hi @j3dyy did you add the analytics.php file within your config directory?

You can do it with the command:
`php artisan vendor:publish --provider="Panakour\Analytics\GoogleAnalyticsServiceProvider"
`

Or manually from the source

**Comment by j3dyy** [comment]
yes @panakour thank you for your response.   i solved this problem , causes on spatie/analytics , both has same config file analytic.php
