### ISSUE TITLE
Request access to another account's analytics data?

### ISSUE THREAD

**Issue by newalphamedia** [panakour/google-analytics#8]
Hello!

Is it possible using this library to request access to someone else's google analytics account with "read only" permissions? For example, you could send someone a link where they follow it and login and accept - your application will then have access to that accounts reporting? This would be quite useful for third parties who need support - do you know if it's possible? I believe it would work with google's "oauth" system, somehow?

Thank you.

**Comment by panakour** [comment]
Hello,
I think it would work following the bellow guide
 https://github.com/panakour/google-analytics#create-credential-with-google-analytics-api-v4

https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/service-php
